### ISSUE TITLE
Compiling ESP32 Arduino

### ISSUE THREAD

**Issue by simon88** [sxjack/uav_electronic_ids#13]
Hi,

I'm trying to use your library but I have an issue when I try to compile with Arduino. But right now I have an error when I try to compile for Adafruit ESP32 feather with wifi.c

> C:\Users\Quentin\Documents\Arduino\libraries\id_open\wifi.c: In function 'odid_wifi_build_nan_sync_beacon_frame':
>
>C:\Users\Quentin\Documents\Arduino\libraries\id_open\wifi.c:235:19: error: 'CLOCK_MONOTONIC' undeclared (first use in this >function)
>     clock_gettime(CLOCK_MONOTONIC, &ts);
                   ^
C:\Users\Quentin\Documents\Arduino\libraries\id_open\wifi.c:235:19: note: each undeclared identifier is reported only once for each function it appears in
Multiple libraries were found for "WiFi.h"
Using library: C:\Users\Quentin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

I've put opendroneid.c, opendroneid.h and odid_wifi.h and wifi.c in `C:\Users\Quentin\Documents\Arduino\libraries\id_open`

here is a screenshot of my lib dir
![image](https://user-images.githubusercontent.com/1391365/151810207-772ea8e9-1a83-4b72-bd84-c3624025761e.png)

and here in id_open dir
![image](https://user-images.githubusercontent.com/1391365/151810279-162346e1-8b26-46f7-b389-c155f267c381.png)

**UPDATE**
I've read this issue [here](https://github.com/sxjack/uav_electronic_ids/issues/6) I've the same issue and I made what you said in your reply but the issue is always here

**UPDATE 2**
Resolved, we need to download the latest version ofn opendroneid and not the 1.0 release

**Comment by simon88** [comment]
Download the latest version of opendroneid and not the 1.0 release

**Comment by sxjack** [comment]
I was about to ask if you had the latest version of wifi.c :-).
