### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by simon88** [sxjack/uav_electronic_ids#14]
Hi,

I'm lokking in the source code, and in `id_open.cpp` line 706 I have this
>   // Pack the WiFi data.
  // One group every 300ms and another every 3000ms.

If I want to change the time for example 300ms to 500ms where is it the ino file or in the lib ?

**Comment by sxjack** [comment]
The timing is controlled by the code starting at line 594. Changing the 74 to 124 would do what you want.

FYI, the 300ms/3s split goes back to an old opendroneid specification and probably should reviewed.

**Comment by simon88** [comment]
Thanks @sxjack , by the way the 300ms/3s is good, acutally in EU for example the maximum time to send packet are 1s/3s
