### ISSUE TITLE
hardware required

### ISSUE THREAD

**Issue by karatemir** [sxjack/uav_electronic_ids#15]
Hi,

[Here](https://github.com/sxjack/uav_electronic_ids/tree/main/id_scanner) ESP32 and either an SH1106 or ST7735 is mentioned as required hardware. In the [picture](https://github.com/sxjack/uav_electronic_ids/blob/main/images/scanner.jpg) on the repo's homepage, there is another board in the middle. Can you please provide its model name and also mention whether it is necessary or not. Thanks.

**Comment by sxjack** [comment]
The board in the middle is a micro SD card module (eg https://uk.banggood.com/Micro-TF-Card-Memory-Shield-Module-SPI-Micro-Storage-Card-Adapter-p-919914.html). Logging to an SD card is an option for the scanner.

OLED (text) and TFT (graphic) displays are options for the scanner. The links are to two that I have used. It should be easy to use another board supported by U8g2 for the text display.

The scanner writes to the serial port so it will work without the SD card or displays.
