### ISSUE TITLE
Some errors that i don't understood 

### ISSUE THREAD

**Issue by Tuburni** [sxjack/uav_electronic_ids#19]
Hello

@sxjack, can you help me with these things?

C:\Users\User\Desktop\uav_electronic_ids-main\uav_electronic_ids-main\id_open\examples\random_flight\id_open.cpp:295:6: error: no declaration matches 'void ID_OpenDrone::set_self_id(char*)'
void ID_OpenDrone::set_self_id(char self_id) {
^~~~~~~~~~~~
C:\Users\User\Desktop\uav_electronic_ids-main\uav_electronic_ids-main\id_open\examples\random_flight\id_open.cpp:295:6: note: no functions named 'void ID_OpenDrone::set_self_id(char)'
In file included from C:\Users\2683126\Desktop\uav_electronic_ids-main\uav_electronic_ids-main\id_open\examples\random_flight\id_open.cpp:54:
C:\Users\User\Desktop\uav_electronic_ids-main\uav_electronic_ids-main\id_open\examples\random_flight\id_open.h:104:7: note: 'class ID_OpenDrone' defined here
class ID_OpenDrone {
^~~~~~~~~~~~

exit status 1

Compilation error: no declaration matches 'void ID_OpenDrone::set_self_id(char*)'

**Comment by sxjack** [comment]
It looks like I forgot to update a file. I'll fix it later this evening.

**Comment by Tuburni** [comment]
@sxjack

Thanks a lot
I will wait a lot
I need this for my graduation project

**Comment by 3-Hydroxytyramine** [comment]
Hello, I have the same problem. I will wait for the fix

**Comment by sxjack** [comment]
Fixed.

**Comment by sxjack** [comment]
If you are studying C++, you really should have realised that it was a missing declaration in the h file.... :-)

**Comment by Tuburni** [comment]
Hello @sxjack

Thank you very much, everything works)))
Sorry I'm a noob in  C++)
