### ISSUE TITLE
Can this be used in Raspberry Pi OS

### ISSUE THREAD

**Issue by punithbm** [sxjack/uav_electronic_ids#2]
Hello @sxjack , We were trying to simulate the open drone id for connecting the drones. we were successfully able to run this test application - https://github.com/opendroneid/opendroneid-core-c in raspberry pi os. Now we are looking to emit this encoded data received from opendroneid-core-c application but not able to figure it out.

Can your please check and let me know wherever we can run this in Raspberry pi os. your help is much appreciated

**Comment by sxjack** [comment]
The code in this repository is for the Arduino IDE on ESP32's.

While it is doubtless possible to modify the classes to run on the Pi, I would say that you would be better off looking at the wifi example in https://github.com/opendroneid/opendroneid-core-c/tree/master/wifi/sender.
