### ISSUE TITLE
id_scanner wifi channel

### ISSUE THREAD

**Issue by michaelzing** [sxjack/uav_electronic_ids#20]
Edit: I realize now that the scanner only scans channel 6 because channel 6 is the channel for wifi nan. I'm wondering if the scanner only works for nan or if it works for wifi beacons as well?

**Comment by sxjack** [comment]
It looks for F3411 WiFi Beacon, NAN and French beacons.

**Comment by michaelzing** [comment]
Got it, thank you. I see that in id_scanner.ino, line 326 sets the wifi channel to channel 6:

`esp_wifi_set_channel(6,WIFI_SECOND_CHAN_NONE);`

Is it possible to change this to scan on another channel in the 2.4 GHz band (i.e. any channel between 1 and 11)?

**Comment by friissoren** [comment]
I will let someone else comment on the functionality of the code, but from a standards perspective, please see the answer [here](https://github.com/sxjack/uav_electronic_ids/issues/21#issuecomment-1522838970).

**Comment by michaelzing** [comment]
thank you, i would still like to see if anyone can comment on the functionality of the code.

**Comment by sxjack** [comment]
> Is it possible to change this to scan on another channel in the 2.4 GHz band (i.e. any channel between 1 and 11)?

Obviously you can change it to whatever you want and/or set the second channel, but if you do, see the comment above the esp_wifi_set_channel call.
