### ISSUE TITLE
id_scanner.io scanning Bluetooth 5 Coded PHY Extended Advertisements?

### ISSUE THREAD

**Issue by Michaelszeng** [sxjack/uav_electronic_ids#23]
Does id_scanner.io have the capability to scan Bluetooth 5 Coded PHY Extended Advertisements as well? Or just Bluetooth 4 legacy advertisements?

**Comment by sxjack** [comment]
id_scanner.ino is only good for WiFi. There is some code in it for BT 4 advertising, but it doesn't work very well.
