### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by gabrielcox** [sxjack/uav_electronic_ids#4]
Are you able to get the debug output to the serial port when DIAGNOSTICS is set to 1 ?  I'm not seeing anything.  I can see the other "Arduino" serial debug output, but not the serial debug messages from C (id_open.cpp).

**Comment by sxjack** [comment]
DIAGNOSTICS only outputs anything for bluetooth. It requires the serial port to be opened in the parent application.

**Comment by sxjack** [comment]
Debug output added for beacons.

ID_OpenDrone::transmit_wifi 187 67+28=95 * 80 ... 37 39 52 | dd 23 90 3a e6 0d 4c | f0 19 01 20 a0 01 ... 00
ID_OpenDrone::transmit_wifi 187 67+28=95 * 80 ... 37 39 52 | dd 23 90 3a e6 0d 4d | f0 19 01 10 02 38 ... 00
ID_OpenDrone::transmit_wifi 187 67+28=95 * 80 ... 37 39 52 | dd 23 90 3a e6 0d 4e | f0 19 01 00 20 47 ... 00
ID_OpenDrone::transmit_wifi 187 67+28=95 * 80 ... 37 39 52 | dd 23 90 3a e6 0d 4f | f0 19 01 10 02 38 ... 00

**Comment by gabrielcox** [comment]
Ah -- of course, I totally missed that I wasn't even hitting those sections. :-D .
This is a good layout of debug (Frame Header | VSIE Header | ODID Message) 👍 .
